src/Entity/Event.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Normalizer\NormalizableInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 */
class Event implements NormalizableInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */

    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="events")
     * @var type User owner
     *
     */
    private $owner;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $place;

    /**
     * @ORM\Column(type="datetime")
     */
    private $opening_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $closing_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $theme;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $website;

    /**
     * @ORM\OneToMany(targetEntity="Product", mappedBy="event", cascade={"remove"})
     */
    private $products;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(groups={"insertion"})
     * @var object
     * @Assert\Image(maxSize = "2M",minWidth="200", minHeight="200")
     */
    private $image;

    public function normalize(NormalizerInterface $serializer, $format = null, array $context = array()): array
    {
        return [
            'name' => $this->getName(),
            'place' => $this->getPlace(),
            'opening_date' => $this->getOpeningDate(),
            'closing_date' => $this->getClosingDate(),
            'description' => $this->getDescription(),
            'phone' => $this->getPhone(),
            'website' => $this->getWebsite(),
            'image' => $this->getImage(),
            'theme' => $this->getTheme()
        ];
    }

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }


    public function getId()
    {
        return $this->id;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getName()
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }


    public function getOwner()
    {
        return $this->owner;
    }

    public function setOwner(User $owner)
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getPlace()
    {
        return $this->place;
    }

    public function setPlace(string $place): self
    {
        $this->place = $place;

        return $this;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getOpeningDate(): DateTimeInterface
    {
        return $this->opening_date;
    }


    public function setOpeningDate(DateTimeInterface $opening_date): self
    {
        $this->opening_date = $opening_date;

        return $this;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getClosingDate(): DateTimeInterface
    {
        return $this->closing_date;
    }

    public function setClosingDate(DateTimeInterface $closing_date): self
    {
        $this->closing_date = $closing_date;

        return $this;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getPhone()
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getTheme()
    {
        return $this->theme;
    }

    public function setTheme(string $theme)
    {
        $this->theme = $theme;

        return $this;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getWebsite()
    {
        return $this->website;
    }

    public function setWebsite(string $website): self
    {
        $this->website = $website;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * @Groups({"searchable"})
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     * @return Event
     */
    public function setDescription($description)
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @Groups({"searchable"})
     */
    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;
        return $this;
    }


}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('place')
            ->add('opening_date')
            ->add('closing_date')
            ->add('phone')
            ->add('theme')
            ->add('website')
            ->add('description')
            ->add('image', FileType::class,
                ['required' => false]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;


// Event Controller

class EventController extends Controller
{

    /**
     * @Route("/events", name="events")
     *
     */
    public function displayEvent(EventRepository $eventRepo)
    {
        $events = $eventRepo->findAll();
        return $this->render('event/events_list_inc.html.twig', [
            'events' => $events
        ]);
    }


    /**
     * @Route("/dashboard/event/add", name="addEvent")
     * @Route("/dashboard/event/edit/{id}", name="editEvent")
     */

    // Function to add and edit an event

    public function addEvent(Request $request, ObjectManager $manager, Event $event = null)
    {
        // 1-Create a new event if no event exist

        // set time only when it's new
        if ($event === null) {
            $event = new Event();
            $event->setOpeningDate(new \DateTime('now'));
            $event->setClosingDate(new \DateTime('tomorrow'));
        } else {
            $oldImage = $event->getImage();
            //transformation dans le format attendu dans le form
            $event->setImage(new File($event->getImage()));
            $group = 'edition';
        }

        $formEvent = $this->createForm(EventType::class, $event)
            ->add('Envoyer', SubmitType::class);


        //2 - validation of the form

        $formEvent->handleRequest($request);

        if ($formEvent->isSubmitted() && $formEvent->isValid()) {
            $event->setOwner($this->getUser());
            //le déplacement du fichier temporaire dans notre fichier upload
            //renommage avec hashage, guessExtension va déduire le type de fichier
            //par le contenu MAIS pour la secu reencodage de l'img normalement
            $image = $event->getImage();
            if ($image === null) {
                $event->setImage($oldImage);
            } else {
                $newFileName = md5(uniqid()) . '.' . $image->guessExtension();
                $image->move('uploads', $newFileName);
                $event->setImage('uploads/' . $newFileName);
            }
            // 3 - Saving the entry in the db
            $manager->persist($event);
            $manager->flush();
            return $this->redirectToRoute('profile');

        }

        return $this->render('event/add_event.html.twig', ['form' => $formEvent->createView()
        ]);
    }


    /**
     * @Route("/dashboard/delete/{id}", name="delete_event")
     */
    //TODO fix circular reference in algolia
    public function deleteEvent(Event $event, ObjectManager $manager)
    {
        $manager->remove($event);
        $manager->flush();
        return $this->redirectToRoute('profile');
    }

    /**
     *
     * @Route("/event/{id}", name="oneEvent")
     */

    // Display an event method to include

    public function display($id)
    {
        $event = $this->getDoctrine()
            ->getRepository(Event::class)
            ->find($id);

        if (!$event) {
            throw $this->createNotFoundException(
                'No event found for id ' . $id
            );
        }
        return $this->render('event/oneEvent.html.twig',
            ['event' => $event]);

    }

    /**
     * @Route("dashboard/listEvent", name="eventListOwner")
     */

    // afficher les événements de l'orga

    public function displayEventByOwner($owner)
    {
        $eventOwner = $this->getDoctrine()
            ->getRepository(Event::class)
            ->find($owner);

        if (!$eventOwner) {
            throw $this->createNotFoundException(
                'No event found for id ' . $owner
            );
        }
        return $this->render('event/event_list_owner_inc.html.twig',
            ['eventOwner' => $eventOwner]);
    }

}

templates/event/add_event.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">

        <h1>Ajouter un Événement </h1>
            {{ form_start(form) }}
            {{ form_widget(form) }}
            {{ form_end(form) }}

    </div>
{% endblock %}

templates/event/event.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello ! ✅</h1>

    This friendly message is coming from:
    <ul>
        {% for event in events %}
        <li>{{ event.name }} {{ event.place }}</li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

templates/event/events_list_inc.html.twig
{% extends 'base.html.twig' %}

{% block body %}


    <div class="container">
        <div id="haut" class="search-bar p-2 m-1">
            <form class="form-horizontal" method="post" accept-charset="utf-8">  <!-- barre de recherche Homepage -->
                <div class="input-group recherche">
                    <i class="fas fa-search fa-2x pl-3 my-auto"></i>
                    <input type="text" id="search-input" autocomplete="off" value=""
                           class=" form-control border-none search-input"
                           placeholder="Que recherchez-vous?">
                    <div class="btn-container">
                        <button type="submit" class="btn-custom">Rechercher</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="row">
            <div id="hits"> <!-- Instantsearch.js -->
                <script type="text/html" id="hit-template">
                    <div id="hit">
                        <a class="card cardlink"
                           href="{{ path('root') }}event/{% verbatim %}{{{ objectID }}}{% endverbatim %}">
                            <img class="card-img-top hit-image" src="{% verbatim %}{{{image}}}{% endverbatim %}"
                                 alt="image de l'évenement"> <!-- image de l'événement -->
                            <div class="card-body pb-3" id="hit-content">
                                <p class="card-subtitle text-muted ">{% verbatim %}{{{_highlightResult.place.value}}}{% endverbatim %}</p>
                                <!-- lieu -->
                                <h4 class="card-title">{% verbatim %}{{{_highlightResult.name.value}}}{% endverbatim %}</h4>
                                <!-- nom de l'événement -->
                                <p class="card-text">{% verbatim %}{{{_highlightResult.description.value}}}{% endverbatim %}</p>
                                <!-- description -->
                                <p class="card-subtitle text-muted">Réservation</p>
                                <hr>
                            </div>
                        </a>
                    </div>
                </script>
            </div>
        </div>
    </div>

    <a href="#haut" class="arrowtop"><i class="fas fa-angle-up fa-3x"></i></a>

    <script src="{{ asset('js/app2.js') }}"></script>
{% endblock %}

templates/event/events_list_owner_inc.html.twig
{% for event in eventOwner %}
    <div class="event-list mt-3 p-2">
        <div class="row">
            <div class="col-6">
                <h4 class="card-title">{{ event.name }}</h4>
                <p class="card-text">{{ event.place }}</p>
                <p class="card-text">{{ event.openingDate|date('Y-m-d') }} - {{ event.closingDate|date('Y-m-d') }}</p>
            </div>
            <div class="col-6 align-self-center text-right">
                <a href="{{ path('oneEvent', { 'id' : event.id }) }}" class="btn btn-danger">Afficher/Modifier
                    l'événement</a>
            </div>
        </div>
    </div>

{% endfor %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>src/Controller/EventController.php</code></li>
        <li>Your template at <code>templates/event/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/event/oneevent.html.twig
{% extends 'base.html.twig' %}

{% block title %} Votre Festival {% endblock %}


{% block header %}
<div class="container-fluid">
    <div class="detailsEvent">
        <img class="img-fluid" src="{{ asset(event.image) }}" alt="{{ event.name }}">
        <!-- affichage de l'image -->
        {% endblock %}
        {% block body %}
        <div class="row">
            <div class="col-md-12 mx-auto">
                <h1>{{ event.name }}</h1> <!-- Nom de l'événement -->
                <hr class="separation">
                <div class="container">
                    <div class="row">
                        <p class="col"><strong>Tel</strong>: 0{{ event.phone }}</p>
                        <p class="col">{{ event.theme }}</p>
                        <p class="col">{{ event.openingDate|date('d/m/Y') }} - {{ event.closingDate|date('d/m/Y') }}</p>
                        <p class="col"><a href="{{ event.website }}"><strong>Website</strong></a></p>
                        <p class="col"><i class="fas fa-map-marker text-danger mr-1"></i>{{ event.place }}</p>
                    </div>
                </div>
                <hr class="separation">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam turpis mi, auctor non rhoncus id,
                    accumsan non tortor. Etiam non bibendum elit. Class aptent taciti sociosqu ad litora torquent per
                    conubia nostra, per inceptos himenaeos. Quisque volutpat orci id erat vestibulum finibus. Nullam
                    congue fringilla posuere. Curabitur dictum nibh sit amet est pulvinar ullamcorper. Maecenas vel
                    libero maximus sem iaculis accumsan quis quis magna. Etiam sit amet nunc eu turpis iaculis tempor.
                    Nam quis mauris in nunc imperdiet dictum. Nam id odio tortor. Donec lacinia convallis augue vel
                    cursus. Ut lorem mauris, malesuada non orci a, posuere scelerisque sapien. Curabitur feugiat tellus
                    est, sed ornare mauris gravida quis. Nunc bibendum blandit lorem, sed malesuada nulla fermentum ac.
                    In tempus ligula sed elit aliquam, non ullamcorper sapien consectetur. Sed ut purus id sapien
                    vulputate pharetra.</p>
                <div class="mx-auto">
                    {% include 'product/event_product_inc.html.twig' with { 'productEvent' : event.products } %}
                    <!-- affichage des produits disponibles -->
                </div>
            </div>
        </div>
    </div>
</div>
{# Orga action list #}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        {% if event.owner.id == app.user.id %}
            <div class="list-group actionorga">
                <a href="#" class="list-group-item list-group-item-action active">
                    ACTIONS
                </a>
                <a href="{{ path('editEvent', {'id' : event.id}) }}" class="list-group-item list-group-item-action">Modifier
                    l'événement</a>
                <a href="{{ path('delete_event', {'id' : event.id}) }}" class="list-group-item list-group-item-action">Supprimer
                    l'événement</a>
                <a href="{{ path('add_product', {'idEvent': event.id}) }}"
                   class="list-group-item list-group-item-action">Ajouter un produit</a>
                <a href="{{ path('profile') }}" class="list-group-item list-group-item-action">Mon compte</a>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}